title: Stewarts Comfy Place
description: Notes and posts to do with software, home automation and AI.
timezone: Pacific/Auckland
remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

header_pages:
- openhab.md
- about.md
